### ISSUE TITLE
crash when reloading ressource packs

### ISSUE THREAD

**Issue by MidyGamy** [opekope2/LiLaC#2]
[crash-2023-09-12_00.25.18-client.txt](https://github.com/opekope2/LiLaC/files/12580798/crash-2023-09-12_00.25.18-client.txt)

**Comment by opekope2** [comment]
It doesn't happen in my development environment or a fresh Minecraft instance (this is the nightmare of developers, "it works on my machine").
Does it happen every time or just once?

**Comment by MidyGamy** [comment]
I saw you fixed it, but yeah, it was every time

**Comment by SoulxluoS** [comment]
I am also experiencing a similar crash, but at startup. 
If only OptiGUI and LiLaC are installed, everything works fine.

But with a certain combination of mods the problem appears. Can't tell the exact mod. Spent a lot of time reinstalling, but each time a new conflicting mod appeared.

I hope that the problem is solved. And so OptiGUI 2.2.0 works fine 
![image](https://github.com/opekope2/LiLaC/assets/70120313/f9f02b59-db75-4a72-9746-bfedb7d82b48)

**Comment by opekope2** [comment]
The problem is that Minecraft start reloading the resources before [ResourceLoader.reload](https://github.com/opekope2/LiLaC/blob/e0f0f82309c9ed04cd2a8d46087e0ba0742cae50/1.19.4/src/main/kotlin/opekope2/lilac/internal/resource/loading/ResourceLoader.kt#L39) returns. I don't know which mod causes this. I implemented a simple and straightforward fix (code reorder).
